language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: o2O2AaWavDR0Klp/C2ereVGbVAzhOhU58bRtwW+6pLV49Y9CRS9fYOxssA0A2N8TeJ4XnH7n+rOUtG2G9+l5d++ui5zfAsulaq710Cpi42MIh5ZJVo7EJJ25d0oDKO4QSENBUExjwFPBfdxeJCs9X6TxfGq5Xz7l8HVlCbJDIKY=
  file:
    - 'iso-639-3.js'
    - 'iso-639-3.min.js'
  on:
    tags: true
